#!/bin/sh

# Run linting inside a nix-shell
nix-shell --run "npx lint-staged"

# Check the exit status of the lint command
if [ $? -ne 0 ]; then
  echo "Linting failed. Commit aborted."
  exit 1
fi

exit 0
